Repository git-ecosystem/git-credential-manager, pull requests merged in 2020-11, with the labels that each got.

#205 Fix missing space in username input
  src/shared/GitHub/GitHubAuthentication.cs
Labels: bug, host:github

#203 Make the system installer always append GCM Core entries, not outright set/replace existing values (and fix a typo)
  src/shared/Microsoft.AzureRepos.Tests/AzureReposHostProviderTests.cs
  src/shared/Microsoft.AzureRepos/AzureReposHostProvider.cs
  src/shared/Microsoft.Git.CredentialManager.Tests/ApplicationTests.cs
  src/shared/Microsoft.Git.CredentialManager.Tests/GitConfigurationTests.cs
  src/shared/Microsoft.Git.CredentialManager/Application.cs
  src/shared/Microsoft.Git.CredentialManager/GitConfiguration.cs
  src/shared/Microsoft.Git.CredentialManager/Settings.cs
  src/shared/TestInfrastructure/Objects/TestGitConfiguration.cs
  src/shared/TestInfrastructure/Objects/TestSettings.cs
  src/windows/Installer.Windows/Setup.iss
Labels: bug, installation, platform:windows

#207 osx-sign: fix macOS release build sign/upload
  .azure-pipelines/templates/osx/pack.signed/step3-pack.yml
Labels: engineering

#212 Allow user to override which interactive authentication flow used for MS auth
  docs/configuration.md
  docs/environment.md
  src/shared/Microsoft.AzureRepos/AzureDevOpsConstants.cs
  src/shared/Microsoft.Git.CredentialManager/Authentication/AuthenticationBase.cs
  src/shared/Microsoft.Git.CredentialManager/Authentication/MicrosoftAuthentication.cs
  src/shared/Microsoft.Git.CredentialManager/Constants.cs
Labels: auth:microsoft, enhancement

#217 Treat empty credential proxy configuration as use system default credentials
  src/shared/Microsoft.Git.CredentialManager.Tests/HttpClientFactoryTests.cs
  src/shared/Microsoft.Git.CredentialManager/HttpClientFactory.cs
Labels: bug

#224 Update GitVersioning package
  Directory.Build.props
Labels: engineering

#221 Create apt-get release pipeline
  .github/configure_repoclient.py
  .github/fetch_release.py
  .github/workflows/build-signed-deb.yml
  .github/workflows/release-apt-get.yml
Labels: engineering

#233 Add suppressions for credscan false positives
  src/shared/GitHub.Tests/GitHubHostProviderTests.cs
  src/shared/GitHub.Tests/GitHubRestApiTests.cs
  src/shared/GitHub/GitHubConstants.cs
  src/shared/Microsoft.Git.CredentialManager.Tests/Authentication/BasicAuthenticationTests.cs
  src/shared/Microsoft.Git.CredentialManager.Tests/Authentication/OAuth2ClientTests.cs
  src/shared/Microsoft.Git.CredentialManager.Tests/Commands/EraseCommandTests.cs
  src/shared/Microsoft.Git.CredentialManager.Tests/Commands/GetCommandTests.cs
  src/shared/Microsoft.Git.CredentialManager.Tests/Commands/StoreCommandTests.cs
  src/shared/Microsoft.Git.CredentialManager.Tests/HostProviderTests.cs
  src/shared/Microsoft.Git.CredentialManager.Tests/HttpRequestExtensionsTests.cs
  src/shared/Microsoft.Git.CredentialManager.Tests/Interop/Linux/SecretServiceCollectionTests.cs
  src/shared/Microsoft.Git.CredentialManager.Tests/Interop/MacOS/MacOSKeychainTests.cs
  src/shared/Microsoft.Git.CredentialManager.Tests/Interop/Posix/GnuPassCredentialStoreTests.cs
  src/shared/Microsoft.Git.CredentialManager.Tests/Interop/Windows/WindowsCredentialManagerTests.cs
  src/shared/Microsoft.Git.CredentialManager.Tests/PlaintextCredentialStoreTests.cs
Labels: external

#234 Match Git config in a mixed-sensitively way
  src/shared/Microsoft.Git.CredentialManager.Tests/GitConfigurationKeyComparerTests.cs
  src/shared/Microsoft.Git.CredentialManager.Tests/GitConfigurationTests.cs
  src/shared/Microsoft.Git.CredentialManager.Tests/SettingsTests.cs
  src/shared/Microsoft.Git.CredentialManager/GitConfigurationKeyComparer.cs
  src/shared/Microsoft.Git.CredentialManager/Settings.cs
  src/shared/TestInfrastructure/Objects/TestGit.cs
  src/shared/TestInfrastructure/Objects/TestGitConfiguration.cs
Labels: bug

#236 Add explicit PAT authentication mode for the GitHub Provider
  src/shared/Atlassian.Bitbucket/BitbucketAuthentication.cs
  src/shared/GitHub.Tests/GitHubHostProviderTests.cs
  src/shared/GitHub/GitHubAuthentication.cs
  src/shared/GitHub/GitHubConstants.cs
  src/shared/GitHub/GitHubHostProvider.cs
  src/shared/Microsoft.Git.CredentialManager.Tests/Authentication/AuthenticationBaseTests.cs
  src/shared/Microsoft.Git.CredentialManager.Tests/EnsureArgumentTests.cs
  src/shared/Microsoft.Git.CredentialManager/Authentication/AuthenticationBase.cs
  src/shared/Microsoft.Git.CredentialManager/EnsureArgument.cs
  src/shared/Microsoft.Git.CredentialManager/TerminalMenu.cs
  src/windows/Atlassian.Bitbucket.UI.Windows/Controls/CredentialsControl.xaml
  src/windows/Atlassian.Bitbucket.UI.Windows/Controls/OAuthControl.xaml
  src/windows/GitHub.UI.Windows/AuthenticationPrompts.cs
  src/windows/GitHub.UI.Windows/Controls/HorizontalShadowDivider.xaml
  src/windows/GitHub.UI.Windows/Login/Login2FaView.xaml
  src/windows/GitHub.UI.Windows/Login/LoginCredentialsView.xaml
  src/windows/GitHub.UI.Windows/Login/LoginCredentialsView.xaml.cs
  src/windows/GitHub.UI.Windows/Login/LoginCredentialsViewModel.cs
  src/windows/GitHub.UI.Windows/Program.cs
  src/windows/GitHub.UI.Windows/Styles.xaml
  src/windows/GitHub.UI.Windows/Tester.xaml
  src/windows/GitHub.UI.Windows/Tester.xaml.cs
  src/windows/Shared.UI.Windows/Controls/DialogWindow.xaml
Labels: enhancement, host:github
