Repository git-ecosystem/git-credential-manager, pull requests merged in 2020-09, with the labels that each got.

#162 Revamp credential storage system to allow for smarter searching
  docs/architecture.md
  docs/configuration.md
  docs/environment.md
  docs/hostprovider.md
  src/shared/Atlassian.Bitbucket/BitbucketHostProvider.cs
  src/shared/GitHub.Tests/GitHubHostProviderTests.cs
  src/shared/GitHub.Tests/GitHubRestApiTests.cs
  src/shared/GitHub/AuthenticationResult.cs
  src/shared/GitHub/GitHubAuthentication.cs
  src/shared/GitHub/GitHubHostProvider.cs
  src/shared/GitHub/GitHubRestApi.cs
  src/shared/Microsoft.AzureRepos.Tests/UriHelpersTests.cs
  src/shared/Microsoft.AzureRepos/AzureReposHostProvider.cs
  src/shared/Microsoft.AzureRepos/UriHelpers.cs
  src/shared/Microsoft.Git.CredentialManager.Tests/Authentication/BasicAuthenticationTests.cs
  src/shared/Microsoft.Git.CredentialManager.Tests/GenericHostProviderTests.cs
  src/shared/Microsoft.Git.CredentialManager.Tests/HostProviderTests.cs
  src/shared/Microsoft.Git.CredentialManager.Tests/InputArgumentsTests.cs
  src/shared/Microsoft.Git.CredentialManager.Tests/Interop/Linux/SecretServiceCollectionTests.cs
  src/shared/Microsoft.Git.CredentialManager.Tests/Interop/MacOS/MacOSKeychainTests.cs
  src/shared/Microsoft.Git.CredentialManager.Tests/Interop/Windows/WindowsCredentialManagerTests.cs
  src/shared/Microsoft.Git.CredentialManager/CommandContext.cs
  src/shared/Microsoft.Git.CredentialManager/Commands/GetCommand.cs
  src/shared/Microsoft.Git.CredentialManager/Constants.cs
  src/shared/Microsoft.Git.CredentialManager/Credential.cs
  src/shared/Microsoft.Git.CredentialManager/GenericHostProvider.cs
  src/shared/Microsoft.Git.CredentialManager/HostProvider.cs
  src/shared/Microsoft.Git.CredentialManager/ICredentialStore.cs
  src/shared/Microsoft.Git.CredentialManager/InputArguments.cs
  src/shared/Microsoft.Git.CredentialManager/Interop/Linux/LinuxCredentialStore.cs
  src/shared/Microsoft.Git.CredentialManager/Interop/Linux/Native/Gobject.cs
  src/shared/Microsoft.Git.CredentialManager/Interop/Linux/Native/Libsecret.cs
  src/shared/Microsoft.Git.CredentialManager/Interop/Linux/SecretServiceCollection.cs
  src/shared/Microsoft.Git.CredentialManager/Interop/Linux/SecretServiceCredential.cs
  src/shared/Microsoft.Git.CredentialManager/Interop/MacOS/MacOSKeychain.cs
  src/shared/Microsoft.Git.CredentialManager/Interop/MacOS/MacOSKeychainCredential.cs
  src/shared/Microsoft.Git.CredentialManager/Interop/MacOS/Native/CoreFoundation.cs
  src/shared/Microsoft.Git.CredentialManager/Interop/MacOS/Native/LibSystem.cs
  src/shared/Microsoft.Git.CredentialManager/Interop/MacOS/Native/SecurityFramework.cs
  src/shared/Microsoft.Git.CredentialManager/Interop/Posix/PosixEnvironment.cs
  src/shared/Microsoft.Git.CredentialManager/Interop/Windows/Native/Advapi32.cs
  src/shared/Microsoft.Git.CredentialManager/Interop/Windows/WindowsCredential.cs
  src/shared/Microsoft.Git.CredentialManager/Interop/Windows/WindowsCredentialManager.cs
  src/shared/Microsoft.Git.CredentialManager/Interop/Windows/WindowsEnvironment.cs
  src/shared/Microsoft.Git.CredentialManager/Settings.cs
  src/shared/TestInfrastructure/Objects/TestCredentialStore.cs
  src/shared/TestInfrastructure/Objects/TestHostProvider.cs
  src/shared/TestInfrastructure/Objects/TestSettings.cs
  src/windows/GitHub.UI.Windows/AuthenticationPrompts.cs
  src/windows/GitHub.UI.Windows/Program.cs
Labels: bug, enhancement

#171 Remove username/password authentication for GitHub.com
  src/shared/GitHub.Tests/GitHubHostProviderTests.cs
  src/shared/GitHub/GitHubConstants.cs
  src/shared/GitHub/GitHubHostProvider.cs
Labels: host:github

#172 Add a variety of credential stores on Linux
  Git-Credential-Manager.sln
  docs/configuration.md
  docs/environment.md
  docs/linuxcredstores.md
  src/shared/Microsoft.Git.CredentialManager.Tests/ApplicationTests.cs
  src/shared/Microsoft.Git.CredentialManager.Tests/Authentication/BasicAuthenticationTests.cs
  src/shared/Microsoft.Git.CredentialManager.Tests/GenericHostProviderTests.cs
  src/shared/Microsoft.Git.CredentialManager.Tests/Interop/Linux/SecretServiceCollectionTests.cs
  src/shared/Microsoft.Git.CredentialManager.Tests/Interop/MacOS/MacOSKeychainTests.cs
  src/shared/Microsoft.Git.CredentialManager.Tests/Interop/Posix/GnuPassCredentialStoreTests.cs
  src/shared/Microsoft.Git.CredentialManager.Tests/Interop/Windows/WindowsCredentialManagerTests.cs
  src/shared/Microsoft.Git.CredentialManager.Tests/PlaintextCredentialStoreTests.cs
  src/shared/Microsoft.Git.CredentialManager/CommandContext.cs
  src/shared/Microsoft.Git.CredentialManager/Constants.cs
  src/shared/Microsoft.Git.CredentialManager/FileCredential.cs
  src/shared/Microsoft.Git.CredentialManager/FileSystem.cs
  src/shared/Microsoft.Git.CredentialManager/Gpg.cs
  src/shared/Microsoft.Git.CredentialManager/Interop/Linux/LinuxCredentialStore.cs
  src/shared/Microsoft.Git.CredentialManager/Interop/Linux/SecretServiceCollection.cs
  src/shared/Microsoft.Git.CredentialManager/Interop/MacOS/MacOSKeychain.cs
  src/shared/Microsoft.Git.CredentialManager/Interop/Posix/GpgPassCredentialStore.cs
  src/shared/Microsoft.Git.CredentialManager/Interop/Windows/WindowsCredentialManager.cs
  src/shared/Microsoft.Git.CredentialManager/PlaintextCredentialStore.cs
  src/shared/Microsoft.Git.CredentialManager/Settings.cs
  src/shared/TestInfrastructure/Objects/TestFileSystem.cs
  src/shared/TestInfrastructure/Objects/TestGpg.cs
  src/shared/TestInfrastructure/Objects/TestSettings.cs
  src/shared/TestInfrastructure/PlatformAttributes.cs
Labels: platform:linux

#174 Add Linux Azure Pipelines release
  .azure-pipelines/release.yml
  .azure-pipelines/templates/linux/pack.unsigned.yml
  .github/workflows/build-installers.yml
  Git-Credential-Manager.sln
  src/linux/Packaging.Linux/Packaging.Linux.csproj
  src/linux/Packaging.Linux/build.sh
Labels: engineering

#175 Fix bug in Git configuration filtering logic
  src/shared/Microsoft.Git.CredentialManager.Tests/GitConfigurationTests.cs
  src/shared/Microsoft.Git.CredentialManager/Git.cs
  src/shared/Microsoft.Git.CredentialManager/GitConfiguration.cs
Labels: bug

#180 Disconnect standard output/error streams from `xdg-open` and friends
  src/shared/Atlassian.Bitbucket/BitbucketAuthentication.cs
  src/shared/GitHub/GitHubAuthentication.cs
  src/shared/Microsoft.Git.CredentialManager/Authentication/OAuth/OAuth2SystemWebBrowser.cs
  src/shared/Microsoft.Git.CredentialManager/BrowserHelper.cs
  src/shared/Microsoft.Git.CredentialManager/EnvironmentBase.cs
  src/shared/Microsoft.Git.CredentialManager/Interop/Posix/PosixEnvironment.cs
  src/shared/Microsoft.Git.CredentialManager/Interop/Windows/WindowsEnvironment.cs
  src/shared/TestInfrastructure/Objects/TestEnvironment.cs
  src/windows/Atlassian.Bitbucket.UI.Windows/ViewModels/CredentialsViewModel.cs
  src/windows/Atlassian.Bitbucket.UI.Windows/ViewModels/OAuthViewModel.cs
  src/windows/GitHub.UI.Windows/Login/Login2FaViewModel.cs
  src/windows/Shared.UI.Windows/ViewModels/WindowViewModel.cs
Labels: auth:oauth, bug, platform:linux

#179 Linux build script updates
  .github/workflows/build-installers.yml
  src/linux/Packaging.Linux/build.sh
Labels: engineering
